CI CD

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -55,11 +55,30 @@ jobs:
             -Dsonar.tests=.
             -Dsonar.test.inclusions=**/*_test.go
             -Dsonar.projectKey=${{ env.PROJECT_NAME }}
-      - uses: sonarsource/sonarqube-quality-gate-action@master
+            -Dsonar.working.directory=.scannerwork
+
+            - name: Check SonarQube report
+            if: always()
+            run: |
+              echo "Checking for report-task.txt"
+              ls -la ./assessment-tax/.scannerwork || true
+              if [ -f "./assessment-tax/.scannerwork/report-task.txt" ]; then
+                echo "Content of report-task.txt:"
+                cat ./assessment-tax/.scannerwork/report-task.txt
+              else
+                echo "report-task.txt not found"
+                echo "Listing contents of assessment-tax directory:"
+                ls -R ./assessment-tax
+              fi
+      - name: SonarQube Quality Gate check
+        uses: sonarsource/sonarqube-quality-gate-action@master
         timeout-minutes: 5
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+        with:
+          scanMetadataReportFile: ./assessment-tax/.scannerwork/report-task.txt
+
   build-and-push-docker-image:
     name: Build Image and Push to Registry
     runs-on: ubuntu-latest
